# Generated by Django 3.2 on 2022-04-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='id_federal',
            new_name='federal_id',
        ),
    ]
