# Generated by Django 3.2 on 2022-04-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this address should be treated as active. Unselect this instead of deleting address.', verbose_name='address active')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('street_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'business_address',
                'verbose_name_plural': 'business_address_list',
                'db_table': 'business_address_db',
            },
        ),
        migrations.CreateModel(
            name='BusinessPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this phone should be treated as active. Unselect this instead of deleting phone.', verbose_name='phone active')),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefone')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_phone', to='businesses.businessaddressmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_phone_author', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business_address_phone',
                'verbose_name_plural': 'business_address_phone_list',
                'db_table': 'business_address_phone_db',
            },
        ),
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='business email address')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição do salão*')),
                ('birth_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Data de criação do salão*')),
                ('federal_id', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='cnpj')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this business should be treated as active. Unselect this instead of deleting business.', verbose_name='business active')),
                ('updated_at', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='business created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, related_name='business_owners', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='business_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'business_list',
                'db_table': 'business_db',
            },
        ),
        migrations.AddField(
            model_name='businessaddressmodel',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='businesses.businessmodel'),
        ),
        migrations.AddField(
            model_name='businessaddressmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_address_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessaddressmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
