# Generated by Django 3.2 on 2022-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcategorymodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this professional category should be treated as active. Unselect this instead of deleting professional category.', verbose_name='business category active'),
        ),
        migrations.AddField(
            model_name='professionalmodel',
            name='federal_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='cnpj'),
        ),
    ]
