# Generated by Django 3.2 on 2022-04-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0003_auto_20220411_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this address should be treated as active. Unselect this instead of deleting address.', verbose_name='phone active')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'professional_phone',
                'verbose_name_plural': 'professional_phone_list',
                'db_table': 'professional_phone_db',
            },
        ),
        migrations.AddConstraint(
            model_name='closeschedulemodel',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date')), ('start_hour__lte', django.db.models.expressions.F('end_hour'))), name='close_start_before'),
        ),
        migrations.AddConstraint(
            model_name='openschedulemodel',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date')), ('start_hour__lte', django.db.models.expressions.F('end_hour'))), name='open_start_before'),
        ),
        migrations.AddConstraint(
            model_name='professionalschedulemodel',
            constraint=models.CheckConstraint(check=models.Q(start_hour__lte=django.db.models.expressions.F('end_hour')), name='schedule_start_before'),
        ),
        migrations.AddField(
            model_name='professionalphonemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_phone_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalphonemodel',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_phone', to='professionals.professionalmodel'),
        ),
        migrations.AddField(
            model_name='professionalphonemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
